### ISSUE TITLE
Failed to load xblock resource

### ISSUE THREAD

**Issue by xcompass** [edx/edx-ora2#736]
Current master is broken on devstack. I got the following error from the console:
```
2015-10-22 01:25:05,749 ERROR 7114 [contentstore.views.xblock] xblock.py:29 - Failed to load xblock resource
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/xblock.py", line 24, in xblock_resource
    content = xblock_class.open_local_resource(uri)
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/core.py", line 76, in open_local_resource
    raise DisallowedFileError("Only files from public/ are allowed: %r" % uri)
DisallowedFileError: Only files from public/ are allowed: u'static/js/src/oa_shared.js'
```

I think this commit 94559a0ff10f0574b3e600e38c6ee060bfa2397e is the cause. It introduced serving non-minified js/css in debug mode. However, it seems xblock doesn't like to serve the content outside of public directory.

Steps to replicate:
* Install the master branch of ORA2
* Create a Peer Assessment problem or go to an existing one
* Page will load not correctly and should see above error message in console.

**Comment by xcompass** [comment]
ping @andy-armstrong

**Comment by andy-armstrong** [comment]
Sorry @xcompass. There's a corresponding change to edx-platform that works with this, but I forgot to merge it first. I'll track it down and make sure that I get it merged today. In the meantime, you can revert this commit locally.

**Comment by andy-armstrong** [comment]
It is this commit that I accidentally put into a working branch. I'll get it into edx-master.

https://github.com/edx/edx-platform/commit/93ff5d16d0ba40ffeca5926f7eeda1ec87d7cf80

**Comment by andy-armstrong** [comment]
Here's a PR with the fix:

https://github.com/edx/edx-platform/pull/10312

**Comment by andy-armstrong** [comment]
@xcompass I've merged the fix into edx-platform now, so please try it again. Sorry for the screw up!

**Comment by xcompass** [comment]
@andy-armstrong No worries. Thanks for the quick fix. it's working now.
