### ISSUE TITLE
feature request: allow urls pasted into open response text to become active links

### ISSUE THREAD

**Issue by JackDougherty** [edx/edx-ora2#949]
We plan to use the Open Response Assessment block in our Data Visualization for All edX course. After students learn how to create their interactive charts and maps on the web, we will ask them to paste their URL into the text box and add a brief description, for peer review by other students.

Problem: Currently, when students paste their URL into the text box, it remains static, and readers need to copy and paste the link into their browser, which adds extra steps. 

Feature request: Would you please modify the code to display urls as active links? See screenshot:

![dataviz-edx-open-response-active-link](https://cloud.githubusercontent.com/assets/649719/20838978/c800797c-b878-11e6-9fcb-faa80760adb6.png)

**Comment by JackDougherty** [comment]
@jbarciauskas @marcotuts - Would you kindly offer some feedback on our request to display urls as active links in ORA?
- Is this a feature that you've considered adding?
- Or if it's not on your priority list, would you consider a pull request from one of our developers? (If so, please suggest where we should start looking in the code to add this.)

**Comment by jbarciauskas** [comment]
@JackDougherty sorry for the delay here! We don't actively monitor GitHub issues, we use JIRA instead.  I'll see if I can get Marco to give some feedback on this.

**Comment by JackDougherty** [comment]
@jbarciauskas thanks for responding, and I look forward to a response. If you and @marcotuts prefer that I email or post elsewhere, let me know.

**Comment by marcotuts** [comment]
Hi @JackDougherty! Thanks for submitting this. I searched and found no open ticket in JIRA on the Teaching and Learning project for this suggestion so I've created one. You can feel free to watch or comment on the issue as well if you'd like to include any other details. 

https://openedx.atlassian.net/browse/TNL-6451

I'm closing this github issue for now. Thanks!
