### ISSUE TITLE
models: course_id limited to 40 characters

### ISSUE THREAD

**Issue by rmoch** [edx/edx-ora2#965]
When using Splitmongo this limitation is quicky reached, I suggest settings course_id fields to 255

**Comment by julAtWork** [comment]
Addendum: this field is an implicit foreign key on courses_course.key that is a varchar 255
It is related to this ticket:
https://openedx.atlassian.net/browse/CRI-52

Impact, it violates integrity constraint in the database and can result in clusters getting out of synchronisation if course name get too long.
It also prevents peer_assessment if name of course is too long.

Also impacts :  

| edxapp       | assessment_aiclassifierset                     | course_id        |                       40 |                    120 | varchar   |
| edxapp       | assessment_aigradingworkflow                   | course_id        |                       40 |                    120 | varchar   |
| edxapp       | assessment_aitrainingworkflow                  | course_id        |                       40 |                    120 | varchar   |
| edxapp       | assessment_peerworkflow                        | course_id        |                       40 |                    120 | varchar   |
| edxapp       | assessment_studenttrainingworkflow             | course_id        |                       40 |                    120 | varchar   |

Correction: change in every model the course_id to 40.

**Comment by OmarIthawi** [comment]
@efischer19 @staubina Please close this issue since it has been solved by #1008.
